import { useState } from 'react'

import { PageHeader } from '../components/layout/PageHeader'
import { Badge } from '../components/ui/Badge'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { EmptyState } from '../components/ui/EmptyState'
import { Skeleton } from '../components/ui/Skeleton'
import { chartUrl, type ChartName } from '../lib/api'

const FIGURES: { name: ChartName; title: string; caption: string; source: string }[] = [
  {
    name: 'tpr-comparison',
    title: 'Detection rate by technique',
    caption:
      'Static baseline against the agentic red agent, per technique. The primary outcome measure.',
    source: 'GET /api/charts/tpr-comparison',
  },
  {
    name: 'mttd-cdf',
    title: 'Time-to-detect distribution',
    caption:
      'Empirical CDF of time to first alert. Curves further left indicate faster detection.',
    source: 'GET /api/charts/mttd-cdf',
  },
  {
    name: 'eps-by-technique',
    title: 'Evasion persistence by technique',
    caption:
      'Early-versus-late detection change per technique. Positive values indicate evasion that persisted.',
    source: 'GET /api/charts/eps-by-technique',
  },
]

export default function Reports() {
  return (
    <>
      <PageHeader
        title="Reports"
        description="Publication-quality figures rendered server-side from the current data. These are the static figures for the written report, distinct from the interactive charts elsewhere."
      />

      <div className="space-y-4 p-5 lg:p-6">
        <div className="rounded border border-border bg-surface-2 px-4 py-2.5">
          <p className="text-[12px] leading-relaxed text-ink-muted">
            These figures are generated by the Python pipeline, not by the browser, so they always
            match the report. The endpoints that serve them are not implemented yet — until they
            are, each slot reports that the figure is unavailable rather than showing a placeholder
            image.
          </p>
        </div>

        {FIGURES.map((figure) => (
          <FigureSlot key={figure.name} {...figure} />
        ))}
      </div>
    </>
  )
}

type LoadState = 'loading' | 'ready' | 'missing'

interface FigureSlotProps {
  name: ChartName
  title: string
  caption: string
  source: string
}

function FigureSlot({ name, title, caption, source }: FigureSlotProps) {
  // Bumping `bust` produces a new src, and the keyed child remounts into a fresh loading
  // state — which is what makes Regenerate show a skeleton instead of a frozen old image.
  const [bust, setBust] = useState<number | null>(null)
  const [downloading, setDownloading] = useState(false)
  const src = chartUrl(name, bust ?? undefined)

  /**
   * Fetch-then-save rather than a plain `download` attribute on a cross-origin link: browsers
   * ignore `download` across origins, so that approach would just open the image in a tab.
   * Pulling the bytes and handing the browser a same-origin object URL makes the save real.
   */
  const download = async () => {
    setDownloading(true)
    try {
      const response = await fetch(src)
      if (!response.ok) throw new Error(`HTTP ${response.status}`)
      const blob = await response.blob()
      const objectUrl = URL.createObjectURL(blob)

      const anchor = document.createElement('a')
      anchor.href = objectUrl
      anchor.download = `${name}.png`
      document.body.appendChild(anchor)
      anchor.click()
      document.body.removeChild(anchor)
      URL.revokeObjectURL(objectUrl)
    } catch {
      // No figure to save, or CORS refused it — show the user the URL rather than nothing.
      window.open(src, '_blank', 'noreferrer')
    } finally {
      setDownloading(false)
    }
  }

  return (
    <Card
      title={title}
      subtitle={caption}
      actions={
        <>
          <span className="hidden font-mono text-[10.5px] text-ink-faint lg:inline">{source}</span>
          <Button size="sm" onClick={() => setBust(Date.now())}>
            Regenerate
          </Button>
          <Button size="sm" loading={downloading} onClick={() => void download()}>
            Download PNG
          </Button>
        </>
      }
    >
      <FigureImage key={bust ?? 'initial'} src={src} alt={title} endpoint={source} />
    </Card>
  )
}

function FigureImage({ src, alt, endpoint }: { src: string; alt: string; endpoint: string }) {
  const [state, setState] = useState<LoadState>('loading')

  return (
    <div className="flex min-h-[320px] flex-col items-center justify-center rounded border border-border bg-surface-2 p-3">
      {state === 'loading' && (
        <div className="w-full space-y-3" aria-busy="true" aria-label={`Loading ${alt}`}>
          <Skeleton className="h-6 w-48" />
          <Skeleton className="h-[260px] w-full" />
          <p className="text-center text-[11.5px] text-ink-faint">
            Requesting figure — matplotlib may be regenerating it from the latest data.
          </p>
        </div>
      )}

      {state === 'missing' && (
        <div className="flex flex-col items-center gap-3 py-10 text-center">
          <Badge tone="neutral" dot>
            Chart not yet available
          </Badge>
          <EmptyState
            title="Figure has not been generated"
            detail={
              <>
                The endpoint <code className="font-mono text-ink-muted">{endpoint}</code> does not
                exist on the backend yet. Once the matplotlib route is added at this exact path, this
                slot renders it with no frontend change.
              </>
            }
          />
        </div>
      )}

      <img
        src={src}
        alt={alt}
        onLoad={() => setState('ready')}
        onError={() => setState('missing')}
        className={`max-w-full ${state === 'ready' ? 'block' : 'hidden'}`}
      />
    </div>
  )
}

